### PR TITLE
Smart Monster!

### PR DESCRIPTION
**Pull request by zzz1999**
You can check them route by SpellParticle.It look like so well.

### CODE REVIEW

**Comment by zzz1999** [comment]
I think it is finished.

**Comment by PetteriM1** [comment]
I'll test that soon when I have time

**Comment by PetteriM1** [comment]
- Why did you make second plugin.yml file? (mob-plugin/plugin.yml)
- Why did you add saveResource for config.yml? There is already saveDefaultConfig (MobPlugin.java line 77)
- You got issue #19 back
- Why did you undo some of my modifications?
- Why did you remove PikyCZ from authors? Lot of stuff in this plugin is made by PikyCZ (in plugin.yml)
- Why did you changed version to 1.0.0 from 1.0?
- Please don't add chinese comments (Example Utils.java line 54-60)

Please answer/fix these then this pr is ready

**Comment by zzz1999** [comment]
1.Wrong do.It is convince to test.Plugin FDevtools can load source file such like this.
2.One chinese said it can fix no content in config.yml.I believe he so i add this.
3.Sorry i will fix it.
4.which modifications is need? I withdraw it.
5.I may be take a old version plugin.yml or it's my worng behavior.I admire PicyCZ.He is a good developer.Remove author PikyCZ is a mistake.
6.It is a better version experssion form.Such like X.X.X
7.Sorry .it is own understand code 's way. My English is poor.I perfer to take a chinese comment to help myself.I forget to delete it.
I will take a modification when i have time.

**Comment by zzz1999** [comment]
I am fix all issue except some of your modifications.I check out.I can't find which your modification is i missing...
Can you tell me which your modification is i leave out?

**Comment by PetteriM1** [comment]
- There is two Rabbit.java files. Remove that what is in /entities/animal/walking/
- Can you please keep version as 1.0
Btw good job!

**Comment by zzz1999** [comment]
yeah!

**Comment by zzz1999** [comment]
done!

**Comment by zzz1999** [comment]
@PetteriM1 let's merge it

**Pull request merged**
