### PR TITLE
.

### PR DESCRIPTION
**Pull request by PikyCZ**
- change version to 0.7
- add PigZombie,Squid,Slime Spawner
- add damage from blocks(lava, cactus)
- format code

### CODE REVIEW

**Comment by zzz1999** [comment]
Good!

**Comment by NycuRO** [comment]
meh

**Comment by PetteriM1** [comment]
You copied this straight from NovaMobsX?

**Comment by PetteriM1** [comment]
Can you please make list of all things what this changes?

**Comment by PikyCZ** [comment]
@PetteriM1  can not I copy my code from my project?

**Comment by PetteriM1** [comment]
Bugs that I found: **(all maybe not because of this pr)**
- Nether mobs take damage from lava
- You can't hit mob what is in lava or take damage from cactus
- Vex have no ai
- Can't use /mob removeall, removeitems or version from console

**Pull request closed without merging**
